In [1]:
# import tensorflow as tf
import mindspore as tf
print(tf.__version__)

ModuleNotFoundError: No module named 'mindspore'

In [2]:
n1 = tf.constant([[3.0,1.5],[3.0,1.5]],tf.float32)
n2 = tf.constant([[4.0,1.5],[3.0,1.5]],tf.float32)
n3 = tf.add(n1,n2)
n3

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[7., 3.],
       [6., 3.]], dtype=float32)>

In [11]:
print(n3.numpy()[1,1])
# print(n3.value)
print(n3.shape)
print(n3.dtype)
print(n3.get_shape())

# print(n3.rank)


3.0
(2, 2)
<dtype: 'float32'>
(2, 2)


In [15]:

#变量,前面是常量 
v1 = tf.Variable([[3.0,1.5],[3.0,1.5]],tf.float32)
v2 = tf.Variable([[4.0,1.5],[3.0,1.5]],tf.float32)
v3 = tf.add(v1,v2)
v1,v2

(<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
 array([[3. , 1.5],
        [3. , 1.5]], dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
 array([[4. , 1.5],
        [3. , 1.5]], dtype=float32)>)

In [13]:
v4 = tf.Variable(n1)

In [14]:
# 变量一般不赋初值, 一定要赋初值是用assign assign_add sub
# 会话
hello = tf.constant('hello,tf')
sess = tf.Session()
print(sess.run(hello))
with sess.as_defaults():
    print(hello.eval())

AttributeError: module 'tensorflow' has no attribute 'Session'